#!/usr/bin/env python3
"""Split the complete REPORT.md record into reader volumes and render every part to PDF.

    .venv-docker/bin/python report/split_report.py

Part I (report/I_SCIENCE.md) is curated by hand and only rendered here. Parts II and III are generated from REPORT.md,
which stays the complete, append-only record that the builders and publishers maintain:

  Part II  report/II_METHODS.md   protocols, accounting, numerical contracts, admissions, drivers and infrastructure
  Part III report/III_RECORD.md   earlier narrative chapters and the per-experiment record, verbatim and in order

Every `## ` section of REPORT.md lands in exactly one of Parts II/III (checked). Classification lives in
report/split_manifest.json: the narrative boundary, machinery title patterns and explicit per-title overrides.
New sections from publishers are classified by the patterns and listed in the run summary. Rerun after any REPORT.md
change; no training, no model imports.
"""
import hashlib
import html
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / 'REPORT.md'
MANIFEST = ROOT / 'report/split_manifest.json'
PARTS = {
    'I': ROOT / 'report/I_SCIENCE.md',
    'II': ROOT / 'report/II_METHODS.md',
    'III': ROOT / 'report/III_RECORD.md',
}
TITLES = {
    'I': 'Part I — The science',
    'II': 'Part II — Methods and machinery',
    'III': 'Part III — Experiment record',
}


def sections(text):
    chunks = re.split(r'(?m)^(?=## )', text)
    return [(c.split('\n', 1)[0][3:].strip(), c.rstrip('\n') + '\n') for c in chunks[1:]]


def classify(secs, manifest):
    patterns = re.compile('|'.join(manifest['machinery_patterns']), re.I)
    overrides = manifest['overrides']
    boundary = next(i for i, (t, _) in enumerate(secs) if t == manifest['narrative_ends_before'])
    out = []
    for i, (title, body) in enumerate(secs):
        if title in overrides:
            part, how = overrides[title], 'override'
        elif i < boundary:
            part, how = 'III-narrative', 'narrative'
        elif patterns.search(title):
            part, how = 'II', 'pattern'
        else:
            part, how = 'III', 'default'
        out.append((part, how, title, body))
    return out


def relink(body):
    """REPORT.md links are relative to the repository root; the parts live in report/."""
    def fix(m):
        bang, label, target = m.group(1), m.group(2), m.group(3)
        if re.match(r'^(https?:|mailto:|#|/)', target):
            return m.group(0)
        target = target[len('report/'):] if target.startswith('report/') else '../' + target
        return f'{bang}[{label}]({target})'
    return re.sub(r'(!?)\[([^\]]*)\]\(([^)\s]+)\)', fix, body)


def generated(part, entries, source_sha, stamp):
    head = [f'# Sleeping Machines — {TITLES[part]}', '',
            f'Generated by `report/split_report.py` from `REPORT.md` (SHA-256 `{source_sha[:16]}…`) on {stamp}. '
            'Do not edit by hand: edit the record or `report/split_manifest.json` and rerun. '
            '[Part I — The science](I_SCIENCE.md) is the reader-facing report; '
            '[Part II — Methods](II_METHODS.md) holds protocols, accounting and implementation checks; '
            '[Part III — Record](III_RECORD.md) holds every experiment entry. '
            '`REPORT.md` remains the complete combined record.', '']
    if part == 'II':
        head += ['This part collects how results are produced and checked: evaluation protocols and metric definitions, '
                 'compute and work accounting, numerical contracts, admission gates, replay drivers, optimizer and '
                 'precision checks, and the hardware cost model. Sections appear in record order.', '']
        groups = [('', entries)]
    else:
        head += ['This part preserves the earlier narrative chapters exactly as published, then every experiment entry '
                 'in record order, wins and losses alike. Part I supersedes the narrative chapters for readers; nothing '
                 'here is deleted or rewritten.', '']
        groups = [('# A. Earlier narrative chapters, as published', [e for e in entries if e[0] == 'III-narrative']),
                  ('# B. Experiment record', [e for e in entries if e[0] == 'III'])]
    toc = ['## Contents', '']
    for heading, group in groups:
        if heading:
            toc.append(f'**{heading[2:]}** ({len(group)} sections)')
            toc.append('')
        toc += [f'{n}. {e[2]}' for n, e in enumerate(group, 1)]
        toc.append('')
    body = []
    for heading, group in groups:
        if heading:
            body += [heading, '']
        body += [relink(e[3]) for e in group]
    text = '\n'.join(head + toc) + '\n' + '\n'.join(body)
    return '\n'.join(line.rstrip() for line in text.splitlines()) + '\n'


# ---------------------------------------------------------------- PDF rendering (reportlab only)

def inline(text):
    text = html.escape(html.unescape(text), quote=False)
    text = re.sub(r'`([^`]+)`', r'<font face="Courier">\1</font>', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])', r'<i>\1</i>', text)
    text = re.sub(r'!\[([^\]]*)\]\(([^)]+)\)', r'\1', text)
    text = re.sub(r'\[([^\]]+)\]\(([^)\s]+)\)', r'<font color="#174a8c">\1</font>', text)
    text = text.replace('&lt;br/&gt;', '<br/>').replace('&lt;br&gt;', '<br/>')
    return text


def render_pdf(md_path, pdf_path, title):
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.platypus import (Image, PageBreak, Paragraph, Preformatted, SimpleDocTemplate, Spacer, Table,
                                    TableStyle)
    import matplotlib
    fonts = Path(matplotlib.get_data_path()) / 'fonts/ttf'
    for name, file in (('DV', 'DejaVuSans.ttf'), ('DVB', 'DejaVuSans-Bold.ttf'), ('DVI', 'DejaVuSans-Oblique.ttf'),
                       ('DVM', 'DejaVuSansMono.ttf')):
        pdfmetrics.registerFont(TTFont(name, str(fonts / file)))
    pdfmetrics.registerFontFamily('DV', normal='DV', bold='DVB', italic='DVI', boldItalic='DVB')
    ink, muted, blue = colors.HexColor('#0b0b0b'), colors.HexColor('#52514e'), colors.HexColor('#2a78d6')
    st = {
        'h0': ParagraphStyle('h0', fontName='DVB', fontSize=20, leading=25, spaceAfter=10, textColor=ink),
        'h1': ParagraphStyle('h1', fontName='DVB', fontSize=15, leading=20, spaceBefore=6, spaceAfter=8, textColor=ink,
                            keepWithNext=1),
        'h2': ParagraphStyle('h2', fontName='DVB', fontSize=12, leading=16, spaceBefore=8, spaceAfter=6, textColor=ink,
                            keepWithNext=1),
        'h3': ParagraphStyle('h3', fontName='DVB', fontSize=10.5, leading=14, spaceBefore=6, spaceAfter=4,
                             textColor=ink, keepWithNext=1),
        'p': ParagraphStyle('p', fontName='DV', fontSize=9.4, leading=13.4, spaceAfter=6, textColor=ink),
        'li': ParagraphStyle('li', fontName='DV', fontSize=9.2, leading=13, leftIndent=12, bulletIndent=2,
                             spaceAfter=3, textColor=ink),
        'cell': ParagraphStyle('cell', fontName='DV', fontSize=7.6, leading=10, textColor=ink),
        'code': ParagraphStyle('code', fontName='DVM', fontSize=7.4, leading=9.4, textColor=ink),
        'cap': ParagraphStyle('cap', fontName='DVI', fontSize=8, leading=11, textColor=muted, spaceAfter=6),
    }
    width = A4[0] - 36 * mm
    base = md_path.parent
    flow = []
    lines = md_path.read_text().splitlines()
    i, first_h1 = 0, True

    def para(text, style):
        try:
            flow.append(Paragraph(inline(text), st[style]))
        except ValueError:
            flow.append(Paragraph(html.escape(text), st[style]))

    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        if line.startswith('```'):
            block = []
            i += 1
            while i < len(lines) and not lines[i].startswith('```'):
                block.append(lines[i])
                i += 1
            i += 1
            flow.append(Preformatted('\n'.join(block), st['code']))
            continue
        m = re.match(r'^(#{1,4}) (.*)', line)
        if m:
            level = len(m.group(1))
            if level == 1:
                if not first_h1:
                    flow.append(PageBreak())
                para(m.group(2), 'h0' if first_h1 else 'h1')
                first_h1 = False
            else:
                para(m.group(2), {2: 'h1', 3: 'h2', 4: 'h3'}[level])
            i += 1
            continue
        m = re.match(r'^!\[([^\]]*)\]\(([^)]+)\)\s*$', line)
        if m:
            target = (base / m.group(2)).resolve()
            if target.suffix == '.svg' and target.with_suffix('.png').exists():
                target = target.with_suffix('.png')
            elif target.suffix == '.svg' and target.exists():
                import pymupdf
                cached = ROOT / 'report/figures/_rendered' / (target.stem + '.png')
                if not cached.exists() or cached.stat().st_mtime < target.stat().st_mtime:
                    cached.parent.mkdir(exist_ok=True)
                    pymupdf.open(str(target))[0].get_pixmap(dpi=200).save(str(cached))
                target = cached
            if target.exists() and target.suffix.lower() in ('.png', '.jpg', '.jpeg'):
                from reportlab.lib.utils import ImageReader
                w, h = ImageReader(str(target)).getSize()
                scale = min(width / w, 150 * mm / h, 1.0 if w < width / 2 else 9e9)
                flow.append(Image(str(target), w * scale, h * scale))
                flow.append(Paragraph(html.escape(m.group(1)), st['cap']))
            else:
                para(f'[Figure: {m.group(1)} — {m.group(2)}]', 'cap')
            i += 1
            continue
        if line.lstrip().startswith('|'):
            rows = []
            while i < len(lines) and lines[i].lstrip().startswith('|'):
                cells = [c.strip() for c in lines[i].strip().strip('|').split('|')]
                if not all(re.fullmatch(r':?-{2,}:?', c) for c in cells if c):
                    rows.append(cells)
                i += 1
            ncol = max(len(r) for r in rows)
            rows = [r + [''] * (ncol - len(r)) for r in rows]
            if any(len(c) > 1800 for r in rows for c in r):
                for r in rows:
                    para(' · '.join(r), 'p')
                continue
            words = [max(len(w) for r in rows for w in (re.sub(r'[*`]', '', r[c]).split() or [''])) for c in range(ncol)]
            lengths = [max(max(min(len(r[c]), 60) for r in rows), words[c] + 2) + 4 for c in range(ncol)]
            total = sum(lengths)
            widths = [width * n / total for n in lengths]
            data = []
            for r in rows:
                row = []
                for c in r:
                    try:
                        row.append(Paragraph(inline(c), st['cell']))
                    except ValueError:
                        row.append(Paragraph(html.escape(c), st['cell']))
                data.append(row)
            table = Table(data, colWidths=widths, repeatRows=1, hAlign='LEFT')
            table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#edf3fb')),
                ('LINEBELOW', (0, 0), (-1, 0), .7, blue),
                ('LINEBELOW', (0, 1), (-1, -1), .25, colors.HexColor('#dbe1e8')),
                ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 3), ('RIGHTPADDING', (0, 0), (-1, -1), 3)]))
            flow.append(table)
            flow.append(Spacer(1, 6))
            continue
        m = re.match(r'^(\s*)([-*]|\d+\.) (.*)', line)
        if m:
            while i < len(lines):
                m = re.match(r'^(\s*)([-*]|\d+\.) (.*)', lines[i])
                if not m:
                    if lines[i].startswith('  ') and lines[i].strip():
                        flow[-1] = Paragraph(flow[-1].text + ' ' + inline(lines[i].strip()), flow[-1].style)
                        i += 1
                        continue
                    break
                indent = len(m.group(1)) // 2
                bullet = '•' if m.group(2) in '-*' else m.group(2)
                style = ParagraphStyle('li%d' % indent, parent=st['li'], leftIndent=12 + 12 * indent,
                                       bulletIndent=2 + 12 * indent)
                try:
                    flow.append(Paragraph(inline(m.group(3)), style, bulletText=bullet))
                except ValueError:
                    flow.append(Paragraph(html.escape(m.group(3)), style, bulletText=bullet))
                i += 1
            flow.append(Spacer(1, 3))
            continue
        block = [line.strip()]
        i += 1
        while i < len(lines) and lines[i].strip() and not re.match(r'^(#{1,4} |!\[|\s*\||\s*([-*]|\d+\.) |```)',
                                                                       lines[i]):
            block.append(lines[i].strip())
            i += 1
        para(' '.join(block), 'p')

    def footer(canvas, doc):
        canvas.saveState()
        canvas.setFont('DV', 7.5)
        canvas.setFillColor(muted)
        canvas.drawString(18 * mm, 9 * mm, f'Sleeping Machines · {title}')
        canvas.drawRightString(A4[0] - 18 * mm, 9 * mm, str(doc.page))
        canvas.restoreState()

    temporary = pdf_path.with_suffix('.building.pdf')
    doc = SimpleDocTemplate(str(temporary), pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=15 * mm,
                            bottomMargin=16 * mm, title=f'Sleeping Machines — {title}',
                            author='Sleeping Machines project')
    doc.build(flow, onFirstPage=footer, onLaterPages=footer)
    temporary.replace(pdf_path)
    return doc.page


def main():
    manifest = json.loads(MANIFEST.read_text())
    text = REPORT.read_text()
    source_sha = hashlib.sha256(text.encode()).hexdigest()
    secs = sections(text)
    entries = classify(secs, manifest)
    assert len(entries) == len(secs) and all(e[0] in ('II', 'III', 'III-narrative') for e in entries)
    missing = [t for t in manifest['overrides'] if t not in {s[0] for s in secs}]
    stamp = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    PARTS['II'].write_text(generated('II', [e for e in entries if e[0] == 'II'], source_sha, stamp))
    PARTS['III'].write_text(generated('III', [e for e in entries if e[0] != 'II'], source_sha, stamp))
    # Every record section appears verbatim (after relinking) in exactly one generated part.
    ii, iii = PARTS['II'].read_text(), PARTS['III'].read_text()
    for part, _, title, body in entries:
        target = ii if part == 'II' else iii
        assert relink(body) in target, title
    pages = {}
    if '--no-pdf' not in sys.argv:
        for key in ('I', 'II', 'III'):
            if PARTS[key].exists():
                pages[key] = render_pdf(PARTS[key], PARTS[key].with_suffix('.pdf'), TITLES[key])
    summary = dict(
        source_sha256=source_sha, sections=len(secs),
        part_II=sum(e[0] == 'II' for e in entries),
        part_III_narrative=sum(e[0] == 'III-narrative' for e in entries),
        part_III_record=sum(e[0] == 'III' for e in entries),
        pattern_classified=[e[2] for e in entries if e[1] == 'pattern' and e[2] not in manifest.get('reviewed', [])],
        unreviewed_default=[e[2] for e in entries if e[1] == 'default' and e[2] not in manifest.get('reviewed', [])],
        stale_overrides=missing, pdf_pages=pages)
    print(json.dumps(summary, indent=2))


if __name__ == '__main__':
    main()
